AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance template

Parameters:
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
  AmiId:
    Description: AMI identifier for the EC2 instance
    Type: String
    Default: ami-0c2d06d50ce30b442

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      ImageId: !Ref 'AmiId'

Outputs:
  PublicIp:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp

#aws cloudformation create-stack --stack-name ec2-stack --template-body file://single-ec2-template.yaml --parameters ParameterKey=InstanceType,ParameterValue=t2.micro ParameterKey=AmiId,ParameterValue=ami-0c2d06d50ce30b442
#aws cloudformation delete-stack --stack-name ec2-stack